### ISSUE TITLE
About the Python version

### ISSUE THREAD

**Issue by ZhouMiaoGX** [liming-ai/ControlNet_Plus_Plus#10]
Hello, I would like to inquire about the Python version you used when running the training code. I encountered some issues while using the Colab installation environment.

**Comment by liming-ai** [comment]
> Hello, I would like to inquire about the Python version you used when running the training code. I encountered some issues while using the Colab installation environment.

Hi, I think there should be no problem with Python version 3.9 or above. What error did you encounter when using Colab?

**Comment by ZhouMiaoGX** [comment]
Sorry to bother you, but I have resolved the issue. The Python version on Colab is 3.10, and the torch version is 2.3.0, but mvcc was not able to compile normally using openmim. I found a solution on mvcc's GitHub, changed the torch version to 2.1.0, and now it compiles normally. Directly compiling using the source code of mvcc should also resolve the issue.

**Comment by ZhouMiaoGX** [comment]
However, due to the limited resources at our school, it might not be possible to successfully train your model. Nevertheless, your idea of loop consistency has been immensely beneficial to me, and I am very grateful for your guidance. I hope to embark on my innovations starting from here!

**Comment by liming-ai** [comment]
> However, due to the limited resources at our school, it might not be possible to successfully train your model. Nevertheless, your idea of loop consistency has been immensely beneficial to me, and I am very grateful for your guidance. I hope to embark on my innovations starting from here!

Glad to know that you have resolved your problems! Thank you for your acknowledge and interest. Feel free to ask if you have any questions!
