### ISSUE TITLE
About normalize

### ISSUE THREAD

**Issue by Strike1999** [liming-ai/ControlNet_Plus_Plus#12]
Thanks for your work!

For image segmentation, you take
`image = normalize(image, (0.485, 0.456, 0.406), (0.229, 0.224, 0.225))`.
However, when inferencing reward model
`outputs = reward_model(image.to(accelerator.device))`,
does this step inherently include image normalization as part of the MMsegmentation test pipeline?

Thanks again.

**Comment by liming-ai** [comment]
> Thanks for your work!
> 
> For image segmentation, you take `image = normalize(image, (0.485, 0.456, 0.406), (0.229, 0.224, 0.225))`. However, when inferencing reward model `outputs = reward_model(image.to(accelerator.device))`, does this step inherently include image normalization as part of the MMsegmentation test pipeline?
> 
> Thanks again.

Thank you for your attention. We call the seg model forward function that defined in MMSeg, instead of directly calling the entire MMSeg Pipeline for inference, so it will not be affected by normalization.

**Comment by b29201746** [comment]
> > Thanks for your work!
> > For image segmentation, you take `image = normalize(image, (0.485, 0.456, 0.406), (0.229, 0.224, 0.225))`. However, when inferencing reward model `outputs = reward_model(image.to(accelerator.device))`, does this step inherently include image normalization as part of the MMsegmentation test pipeline?
> > Thanks again.
> 
> Thank you for your attention. We call the seg model forward function that defined in MMSeg, instead of directly calling the entire MMSeg Pipeline for inference, so it will not be affected by normalization.

Sorry, but I'm having some difficulty understanding what that means. 
Could you please let me know

**Comment by liming-ai** [comment]
Hi @b29201746,

Sorry to reply late, during our code, we directly call the forward function of the reward model, instead of calling the forward function of the MMSeg Pipeline. Since the normalization is integrated into the MMSeg Pipeline Forward instead of Model Forward, the normalization in our training code would NOT be affected by the MMSeg normalization.

**Comment by b29201746** [comment]
> Hi @b29201746,
> 
> Sorry to reply late, during our code, we directly call the forward function of the reward model, instead of calling the forward function of the MMSeg Pipeline. Since the normalization is integrated into the MMSeg Pipeline Forward instead of Model Forward, the normalization in our training code would NOT be affected by the MMSeg normalization.

OK, I understand! Thank you so much for taking the time to inform me and provide detailed explanation!
