### ISSUE TITLE
Arxiv Link Error

### ISSUE THREAD

**Issue by HenryQUQ** [liming-ai/ControlNet_Plus_Plus#14]
Kindly remind that there is an extra semicolon after your project link on the Arxiv page.

**Comment by liming-ai** [comment]
> Kindly remind that there is an extra semicolon after your project link on the Arxiv page.

Thanks a lot for your remind, I will fix it as soon as possible.

**Comment by liming-ai** [comment]
> > Kindly remind that there is an extra semicolon after your project link on the Arxiv page.
> 
> Thanks a lot for your remind, I will fix it as soon as possible.

Thanks again for your kindly remind, I already fix this problem
