### ISSUE TITLE
About VRAM

### ISSUE THREAD

**Issue by KuonjiAlice514** [liming-ai/ControlNet_Plus_Plus#17]
Thanks for your great work!
And I would like to know the amount of VRAM required for training. Can a single 2080 Ti be used for training?

**Comment by liming-ai** [comment]
> Thanks for your great work! And I would like to know the amount of VRAM required for training. Can a single 2080 Ti be used for training?

Hi @KuonjiAlice514, I do not think a single 2080Ti is enough for training. We strongly recommend for 8 GPUs with 48GB memory at least
