### ISSUE TITLE
How to implement Equation 7 in your paper with diffusers? Thanks in advance.

### ISSUE THREAD

**Issue by CXNing** [liming-ai/ControlNet_Plus_Plus#6]

**Comment by liming-ai** [comment]
> _No description provided._

Thanks for your question. Please wait for us to release the training code, which is expected to be at the end of this month or early June.

**Comment by BJQ123456** [comment]
Great work! I would like to ask why the input for the predicted noise in Equation 7 is 𝑡−1 instead of 𝑡 ? Looking forward to your response, thank you.

**Comment by liming-ai** [comment]
Hi @CXNing @BJQ123456 
Now we have released the training, evaluation code. Please refer to the implementation.
